<a href="https://colab.research.google.com/github/eldertree777/tensorflow1/blob/master/%EC%95%84%EC%9D%B4%EB%A6%AC%EC%8A%A4_%ED%92%88%EC%A2%85_%EB%B6%84%EB%A5%98.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# 아이리스 품종 분류
  - github csv url: https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv

In [1]:
#라이브러리 사용
import tensorflow as tf
import pandas as pd

In [53]:
#과거의 데이터 준비하기
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
아이리스 = pd.read_csv(파일경로)
print(아이리스.columns)
아이리스.head()

Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종'], dtype='object')


꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa
2   4.7  3.2    1.3   0.2  setosa
3   4.6  3.1    1.5   0.2  setosa
4   5.0  3.6    1.4   0.2  setosa

In [54]:
# 원핫인코딩
인코딩 = pd.get_dummies(아이리스)
인코딩.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
0   5.1  3.5    1.4   0.2          1              0             0
1   4.9  3.0    1.4   0.2          1              0             0
2   4.7  3.2    1.3   0.2          1              0             0
3   4.6  3.1    1.5   0.2          1              0             0
4   5.0  3.6    1.4   0.2          1              0             0

In [55]:
print(인코딩.columns)

Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종_setosa', '품종_versicolor',
       '품종_virginica'],
      dtype='object')


In [56]:
# 독립변수, 종속변수
독립 = 인코딩[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속 = 인코딩[['품종_setosa', '품종_versicolor',
       '품종_virginica']]
print(독립.shape, 종속.shape)

(150, 4) (150, 3)


In [57]:
# 모델의 구조를 만듭니다.
x = tf.keras.layers.Input(shape = [4])
y = tf.keras.layers.Dense(3, activation='softmax')(x)
model = tf.keras.models.Model(x,y)
model.compile(loss = 'categorical_crossentropy' , metrics = 'accuracy')

In [61]:
# 학습을 시킵니다.
model.fit(독립,종속, epochs= 100 , verbose = 1)

Epoch 1/100
5/5 [==============================] - 0s 1ms/step - loss: 0.3905 - accuracy: 0.9467
Epoch 2/100
5/5 [==============================] - 0s 1ms/step - loss: 0.3899 - accuracy: 0.9400
Epoch 3/100
5/5 [==============================] - 0s 2ms/step - loss: 0.3888 - accuracy: 0.9400
Epoch 4/100
5/5 [==============================] - 0s 1ms/step - loss: 0.3878 - accuracy: 0.9400
Epoch 5/100
5/5 [==============================] - 0s 2ms/step - loss: 0.3877 - accuracy: 0.9467
Epoch 6/100
5/5 [==============================] - 0s 2ms/step - loss: 0.3864 - accuracy: 0.9467
Epoch 7/100
5/5 [==============================] - 0s 2ms/step - loss: 0.3856 - accuracy: 0.9467
Epoch 8/100
5/5 [==============================] - 0s 2ms/step - loss: 0.3841 - accuracy: 0.9467
Epoch 9/100
5/5 [==============================] - 0s 1ms/step - loss: 0.3831 - accuracy: 0.9533
Epoch 10/100
5/5 [==============================] - 0s 2ms/step - loss: 0.3825 - accuracy: 0.9533
Epoch 11/100
5/5 [===========

In [62]:
# 모델을 이용합니다. 
# 맨 처음 데이터 5개
print(model.predict(독립[:5]))
print(종속[:5])

# 맨 마지막 데이터 5개
print(model.predict(독립[-5:]))
print(종속[-5:])

[[0.96354175 0.03510298 0.00135532]
 [0.92996037 0.06730231 0.00273739]
 [0.95148253 0.04637578 0.0021417 ]
 [0.9327548  0.06365559 0.00358961]
 [0.9682433  0.03045816 0.0012985 ]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0
[[0.00103232 0.30419734 0.6947703 ]
 [0.00197002 0.40728283 0.5907471 ]
 [0.00226726 0.35531253 0.6424202 ]
 [0.00095747 0.19090965 0.8081328 ]
 [0.00359873 0.32395342 0.67244786]]
     품종_setosa  품종_versicolor  품종_virginica
145          0              0             1
146          0              0             1
147          0              0             1
148          0              0             1
149          0              0             1


In [49]:
print(종속[-5:])

     품종_setosa  품종_versicolor  품종_virginica
145          0              0             1
146          0              0             1
147          0              0             1
148          0              0             1
149          0              0             1


In [63]:
# 학습한 가중치
model.get_weights()

[array([[-0.26667655, -0.19865249, -0.9808955 ],
        [ 1.1772987 , -0.22267519, -0.01389603],
        [-1.12805   , -0.11108171,  0.6008589 ],
        [-1.9797378 ,  0.0797364 ,  1.3800972 ]], dtype=float32),
 array([ 0.8911743 ,  0.29618013, -0.95614535], dtype=float32)]