<a href="https://colab.research.google.com/github/eldertree777/tensorflow1/blob/master/%ED%9E%88%EB%93%A0%EB%A0%88%EC%9D%B4%EC%96%B4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# 히든레이어
  -보스턴 집값 예측: https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv

  -아이리스 품종 분류: https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv

In [1]:
# 라이브러리 사용
import tensorflow as tf
import pandas as pd

# 보스턴 집값 예측

In [3]:
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv'
보스턴 = pd.read_csv(파일경로)
print(보스턴.columns)

Index(['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat', 'medv'],
      dtype='object')


In [4]:
독립 = 보스턴[['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat']] 
종속 = 보스턴[['medv']]

print(독립.shape, 종속.shape)

(506, 13) (506, 1)


In [12]:
X = tf.keras.layers.Input(shape=[13])
H = tf.keras.layers.Dense(10,activation = 'swish')(X)
Y = tf.keras.layers.Dense(1)(H)
model = tf.keras.models.Model(X,Y)
model.compile(loss='mse', metrics = 'accuracy')

In [14]:
model.summary()

Model: "functional_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_5 (InputLayer)         [(None, 13)]              0         
_________________________________________________________________
dense_4 (Dense)              (None, 10)                140       
_________________________________________________________________
dense_5 (Dense)              (None, 1)                 11        
Total params: 151
Trainable params: 151
Non-trainable params: 0
_________________________________________________________________


In [13]:
model.fit(독립,종속, epochs=10000 ,verbose= 0)
model.fit(독립,종속, epochs=10)

Epoch 1/10
16/16 [==============================] - 0s 2ms/step - loss: 12.0810 - accuracy: 0.0000e+00
Epoch 2/10
16/16 [==============================] - 0s 1ms/step - loss: 11.9402 - accuracy: 0.0000e+00
Epoch 3/10
16/16 [==============================] - 0s 1ms/step - loss: 11.2498 - accuracy: 0.0000e+00
Epoch 4/10
16/16 [==============================] - 0s 1ms/step - loss: 12.3983 - accuracy: 0.0000e+00
Epoch 5/10
16/16 [==============================] - 0s 1ms/step - loss: 11.9488 - accuracy: 0.0000e+00
Epoch 6/10
16/16 [==============================] - 0s 1ms/step - loss: 12.0975 - accuracy: 0.0000e+00
Epoch 7/10
16/16 [==============================] - 0s 1ms/step - loss: 12.3609 - accuracy: 0.0000e+00
Epoch 8/10
16/16 [==============================] - 0s 1ms/step - loss: 11.9529 - accuracy: 0.0000e+00
Epoch 9/10
16/16 [==============================] - 0s 1ms/step - loss: 12.1060 - accuracy: 0.0000e+00
Epoch 10/10
16/16 [==============================] - 0s 1ms/step - loss: 

In [16]:
print(model.predict(독립[:5]))
print(종속[:5])

[[26.035706]
 [24.514286]
 [33.153797]
 [32.427757]
 [33.56096 ]]
   medv
0  24.0
1  21.6
2  34.7
3  33.4
4  36.2


# 아이리스 품종분류

In [20]:
파일경로 ='https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
아이리스 = pd.read_csv(파일경로)

In [21]:
아이리스 = pd.get_dummies(아이리스)

In [22]:
print(아이리스.columns)

Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종_setosa', '품종_versicolor',
       '품종_virginica'],
      dtype='object')


In [23]:
독립 = 아이리스[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']] 
종속 = 아이리스[['품종_setosa', '품종_versicolor',
       '품종_virginica']]
print(독립.shape , 종속.shape)

(150, 4) (150, 3)


In [24]:
X = tf.keras.layers.Input(shape=[4])
H = tf.keras.layers.Dense(5,activation = "swish")(X)
H = tf.keras.layers.Dense(5,activation = "swish")(H)
H = tf.keras.layers.Dense(5,activation = "swish")(H)
Y = tf.keras.layers.Dense(3, activation='softmax')(H)
model = tf.keras.models.Model(X,Y)
model.compile(loss='categorical_crossentropy',
              metrics='accuracy')

In [ ]:
model.fit(독립,종속, epochs= 100)

In [26]:
print(model.predict(독립[0:5]))

[[0.64891374 0.26264608 0.08844023]
 [0.65962964 0.25856945 0.08180089]
 [0.6598592  0.24565504 0.09448578]
 [0.6632623  0.25177807 0.08495965]
 [0.64800316 0.258954   0.09304279]]


In [27]:
print(종속[0:5])

   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0
